INSERT INTO products(name, desc, price) VALUES('MORINGA SHAKER', 'Shake up the world', 45.92);
INSERT INTO products(name, desc, price) VALUES('MORINGA TEA BAGS', 'Sip your way to wellness', 18.50);
INSERT INTO products(name, desc, price) VALUES('MORINGA BODY LOTION', 'Glow with nature', 30.25);
INSERT INTO products(name, desc, price) VALUES('MORINGA FACE MASK', 'Pure skin therapy', 28.90);
INSERT INTO products(name, desc, price) VALUES('MORINGA LEAF POWDER', 'Nature in a scoop', 15.00);
INSERT INTO products(name, desc, price) VALUES('MORINGA PROTEIN BAR', 'Snack healthy', 5.99);
INSERT INTO products(name, desc, price) VALUES('MORINGA BOOSTER', 'Energize your mornings', 52.99);
INSERT INTO products(name, desc, price) VALUES('MORINGA ENERGY DRINK', 'Power in every sip', 3.99);
INSERT INTO products(name, desc, price) VALUES('MORINGA VITAMINS', 'Daily dose of vitality', 20.75);
INSERT INTO products(name, desc, price) VALUES('MORINGA SOAP', 'Clean and green', 7.80);
INSERT INTO products(name, desc, price) VALUES('MORINGA SHAMPOO', 'Refresh your roots', 22.60);
INSERT INTO products(name, desc, price) VALUES('MORINGA CONDITIONER', 'Silky smooth naturally', 23.10);
INSERT INTO products(name, desc, price) VALUES('MORINGA CAPSULES', 'Health in a capsule', 19.95);
INSERT INTO products(name, desc, price) VALUES('MORINGA INFUSED HONEY', 'Sweet wellness', 25.40);
INSERT INTO products(name, desc, price) VALUES('MORINGA HAND SANITIZER', 'Clean hands, naturally', 4.50);
INSERT INTO products(name, desc, price) VALUES('MORINGA HAIR OIL', 'Nourish and grow', 16.75);
INSERT INTO products(name, desc, price) VALUES('MORINGA OIL DROPS', 'Nature’s elixir', 29.60);
INSERT INTO products(name, desc, price) VALUES('MORINGA BREW', 'Brewed health', 11.99);
INSERT INTO products(name, desc, price) VALUES('MORINGA SMOOTHIE MIX', 'Blend and boost', 14.25);
INSERT INTO products(name, desc, price) VALUES('MORINGA DETOX PACK', 'Cleanse the smart way', 34.00);
INSERT INTO products(name, desc, price) VALUES('MORINGA GUMMY BEARS', 'Healthy and fun', 12.50);
INSERT INTO products(name, desc, price) VALUES('MORINGA SNACK CRISPS', 'Crunch into health', 6.70);
INSERT INTO products(name, desc, price) VALUES('MORINGA CHOCOLATE BAR', 'Deliciously healthy', 4.20);
INSERT INTO products(name, desc, price) VALUES('MORINGA TOOTHPASTE', 'Smile with nature', 5.80);
INSERT INTO products(name, desc, price) VALUES('MORINGA EYE SERUM', 'Brighten naturally', 26.10);
INSERT INTO products(name, desc, price) VALUES('MORINGA BEARD BALM', 'Groom with greens', 17.50);
INSERT INTO products(name, desc, price) VALUES('MORINGA LIP BALM', 'Nature’s kiss', 3.95);
INSERT INTO products(name, desc, price) VALUES('MORINGA FOOT CREAM', 'Soothe your step', 12.85);
INSERT INTO products(name, desc, price) VALUES('MORINGA CLEANSING WIPES', 'Clean on the go', 6.25);
INSERT INTO products(name, desc, price) VALUES('MORINGA INSTANT MIX', 'Quick health fix', 13.40);
INSERT INTO products(name, desc, price) VALUES('MORINGA SEEDS PACK', 'Grow your health', 10.00);
INSERT INTO products(name, desc, price) VALUES('MORINGA TEA INFUSER', 'Perfect tea, every time', 9.90);
INSERT INTO products(name, desc, price) VALUES('MORINGA COFFEE BLEND', 'Wake up green', 19.95);
INSERT INTO products(name, desc, price) VALUES('MORINGA WELLNESS KIT', 'All-in-one care', 59.99);
INSERT INTO products(name, desc, price) VALUES('MORINGA CANDLE', 'Breathe wellness', 15.80);
INSERT INTO products(name, desc, price) VALUES('MORINGA ROOM SPRAY', 'Refresh your space', 8.75);
INSERT INTO products(name, desc, price) VALUES('MORINGA SKIN TONER', 'Tone the natural way', 21.50);
INSERT INTO products(name, desc, price) VALUES('MORINGA FACE SCRUB', 'Exfoliate with love', 18.20);
INSERT INTO products(name, desc, price) VALUES('MORINGA BABY LOTION', 'Gentle care for little ones', 14.35);
INSERT INTO products(name, desc, price) VALUES('MORINGA PET SUPPLEMENT', 'Health for your pet', 24.99);
INSERT INTO products(name, desc, price) VALUES('MORINGA COOKING OIL', 'Cook smart', 32.00);
INSERT INTO products(name, desc, price) VALUES('MORINGA GRANOLA', 'Crunch with purpose', 7.60);
INSERT INTO products(name, desc, price) VALUES('MORINGA SLEEP TEA', 'Relax and recharge', 16.95);
INSERT INTO products(name, desc, price) VALUES('MORINGA CEREAL', 'Smart breakfast choice', 9.50);
INSERT INTO products(name, desc, price) VALUES('MORINGA ENERGY SHOT', 'Boost in a bottle', 3.40);
INSERT INTO products(name, desc, price) VALUES('MORINGA SOOTHING BALM', 'Relief the natural way', 8.30);
INSERT INTO products(name, desc, price) VALUES('MORINGA SPREAD', 'Green on toast', 5.45);
INSERT INTO products(name, desc, price) VALUES('MORINGA BATH SALTS', 'Soak in serenity', 13.99);
INSERT INTO products(name, desc, price) VALUES('MORINGA NIGHT CREAM', 'Repair as you rest', 22.00);
INSERT INTO products(name, desc, price) VALUES('MORINGA SUNSCREEN', 'Guard with green', 19.75);
INSERT INTO products(name, desc, price) VALUES('MORINGA CLEANSER', 'Gentle deep clean', 20.10);
INSERT INTO products(name, desc, price) VALUES('MORINGA NOSE STRIPS', 'Clear naturally', 6.20);
INSERT INTO products(name, desc, price) VALUES('MORINGA DETAN PACK', 'Reverse the sun', 17.80);
INSERT INTO products(name, desc, price) VALUES('MORINGA MOISTURIZER', 'Stay soft, stay green', 18.50);
INSERT INTO products(name, desc, price) VALUES('MORINGA WHITENING SERUM', 'Glow up, naturally', 24.60);
INSERT INTO products(name, desc, price) VALUES('MORINGA MULTIVITAMIN', 'Complete daily support', 22.90);
INSERT INTO products(name, desc, price) VALUES('MORINGA IMMUNE BOOST', 'Shield your body', 25.00);
INSERT INTO products(name, desc, price) VALUES('MORINGA SPICE MIX', 'Flavor meets function', 6.99);
INSERT INTO products(name, desc, price) VALUES('MORINGA BODY WASH', 'Green freshness', 12.20);
INSERT INTO products(name, desc, price) VALUES('MORINGA MAKEUP REMOVER', 'Clean face, clean feel', 9.70);
INSERT INTO products(name, desc, price) VALUES('MORINGA EYE PATCHES', 'Eyes love green', 15.50);
INSERT INTO products(name, desc, price) VALUES('MORINGA HAIR MASK', 'Deep care therapy', 19.20);
INSERT INTO products(name, desc, price) VALUES('MORINGA GEL', 'Cool and calm', 11.60);
INSERT INTO products(name, desc, price) VALUES('MORINGA SALAD DRESSING', 'Pour on the goodness', 7.45);
INSERT INTO products(name, desc, price) VALUES('MORINGA BATH BOMB', 'Explode into freshness', 5.95);
INSERT INTO products(name, desc, price) VALUES('MORINGA BEARD OIL', 'Tame the wild', 13.30);
INSERT INTO products(name, desc, price) VALUES('MORINGA BABY SHAMPOO', 'Gentle bubbles', 10.80);
INSERT INTO products(name, desc, price) VALUES('MORINGA MASSAGE OIL', 'Glide into calm', 21.40);
INSERT INTO products(name, desc, price) VALUES('MORINGA HAND CREAM', 'Softness in a tube', 7.99);