  name: Java CI with Maven | deploy to ECR

  on:
    push:
      branches:
        - main  # or your default branch

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: Build with Maven
          run: mvn -B package --file pom.xml
          #-DskipTests

        - name: Zip Java artifact
          run: |
            mkdir -p release
            cp target/*.jar release/
            zip -j release/app.zip release/*.jar

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Configure docker to AWS ECR
          run: |
            aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 495599742316.dkr.ecr.eu-central-1.amazonaws.com

        - name: Upload zipped app to ECR
          run: |
            docker push 495599742316.dkr.ecr.eu-central-1.amazonaws.com/bassell-registry:latest
# aws s3 cp app.zip s3://bassell-cicd-lab-bucket/app.zip