name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Prepare deployment zip (JAR + Procfile)
      - name: Prepare bundle
        run: |
          mkdir deploy
          cp target/*.jar deploy/
          cp Procfile deploy/
          cd deploy
          zip -r app-bundle.zip .

      # Upload to S3
      - name: Upload to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          region: ${{ secrets.AWS_REGION }}
          source: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
